name: My_first_workflow

on:
  push:
    branches:
      - main
  
jobs: 
  hello_world:

    runs-on: ubuntu-latest

    steps:
      - name: hello World
        run: echo "Hello world from github actions"

  hello_world2:

    runs-on: ubuntu-latest

    steps:
      - name: hello World
        run: echo "Hello world from github actions"

  hello_world3:

    runs-on: ubuntu-latest

    steps:
      - name: hello World
        run: echo "Hello world from github actions"



