name: My_first_workflow

on:
  push:
    branches:
      - main
  
job: 
  hello_world:

    runs-on: ubuntu-latest

    steps:
      - name: hello World
        run: echo "Hello world from github actions"



